name: rag_chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.1=h9a5124b_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.12=h18782d2_1_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_3
  - tzdata=2025b=h8577fbf_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - beautifulsoup4==4.14.3
      - bs4==0.0.2
      - certifi==2025.11.12
      - click==8.3.1
      - distro==1.9.0
      - dotenv==0.9.9
      - fastapi==0.124.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jiter==0.12.0
      - lxml==6.0.2
      - openai==2.11.0
      - psycopg2-binary==2.9.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.45
      - starlette==0.50.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uvicorn==0.38.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/rag_chatbot
