name: rag_chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - python=3.12.12=h18782d2_1_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_3
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - beautifulsoup4==4.14.2
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - distro==1.9.0
      - fastapi==0.121.2
      - google-auth==2.43.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jiter==0.12.0
      - lxml==6.0.2
      - numpy==2.3.4
      - openai==2.8.0
      - pgvector==0.4.1
      - pip==24.3.1
      - protobuf==6.33.1
      - psycopg2-binary==2.9.11
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - regex==2025.11.3
      - requests==2.32.5
      - rsa==4.9.1
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - starlette==0.49.3
      - tenacity==9.1.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - websockets==15.0.1
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/rag_chatbot
